# Copyright Diagnostic Image Analysis Group, Radboudumc, Nijmegen, The Netherlands
# Licensed under Apache-2.0

def get_entries_file(experiment_name, dataset_name):
    experiment = EXPERIMENTS[experiment_name]
    dataset = next((d for d in experiment['datasets'] if d['name'] == dataset_name), None)
    return dataset['entries_file']

rule compute_features_ctfm:
    input:
        entries_file = lambda wildcards: DATASET_ROOT + f"/{wildcards.dataset_name}/{get_entries_file('ctfm', wildcards.dataset_name)}_fold{wildcards.fold}.json"
    output:
        output_features_training = OUTPUT_ROOT + "/ctfm/{epoch}/{dataset_name}/fold{fold}/features/modalities/{modality}/training.npz",
        output_features_test = OUTPUT_ROOT + "/ctfm/{epoch}/{dataset_name}/fold{fold}/features/modalities/{modality}/test.npz"
    resources:
        image = "jtagscherer/evalblocks-ctfm:0.0.1",
        qos="low",
        cpus=16,
        gpus=1,
        mem_mb=32000,
        time="1-00:00:00"
    shell:
        """
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m featuremodels.scripts.ctfm \
                --entries-file {input.entries_file} \
                --output-features-training {output.output_features_training} \
                --output-features-test {output.output_features_test}"
        """

rule compute_features_curia:
    input:
        entries_file = lambda wildcards: DATASET_ROOT + f"/{wildcards.dataset_name}/{get_entries_file('curia', wildcards.dataset_name)}_fold{wildcards.fold}.json"
    output:
        output_features_training = OUTPUT_ROOT + "/curia/{epoch}/{dataset_name}/fold{fold}/features/modalities/{modality}/training.npz",
        output_features_test = OUTPUT_ROOT + "/curia/{epoch}/{dataset_name}/fold{fold}/features/modalities/{modality}/test.npz"
    resources:
        image = "jtagscherer/evalblocks-huggingface:0.0.1",
        qos="low",
        cpus=16,
        gpus=1,
        mem_mb=32000,
        time="1-00:00:00"
    shell:
        """
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "export HF_HOME={HF_HOME} && \
            cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m featuremodels.scripts.curia \
                --entries-file {input.entries_file} \
                --output-features-training {output.output_features_training} \
                --output-features-test {output.output_features_test} \
                --modality {wildcards.modality}"
        """

rule compute_features_umedpt:
    input:
        entries_file = lambda wildcards: DATASET_ROOT + f"/{wildcards.dataset_name}/{get_entries_file('umedpt', wildcards.dataset_name)}_fold{wildcards.fold}.json"
    output:
        output_features_training = OUTPUT_ROOT + "/umedpt/{epoch}/{dataset_name}/fold{fold}/features/modalities/{modality}/training.npz",
        output_features_test = OUTPUT_ROOT + "/umedpt/{epoch}/{dataset_name}/fold{fold}/features/modalities/{modality}/test.npz"
    resources:
        image = "jtagscherer/evalblocks-umedpt:0.0.1",
        qos="low",
        cpus=16,
        gpus=1,
        mem_mb=32000,
        time="1-00:00:00"
    shell:
        """
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m featuremodels.scripts.umedpt \
                --entries-file {input.entries_file} \
                --output-features-training {output.output_features_training} \
                --output-features-test {output.output_features_test} \
                --modality {wildcards.modality}"
        """

rule compute_features_spectre:
    input:
        entries_file = lambda wildcards: DATASET_ROOT + f"/{wildcards.dataset_name}/{get_entries_file('curia', wildcards.dataset_name)}_fold{wildcards.fold}.json"
    output:
        output_features_training = OUTPUT_ROOT + "/spectre/{epoch}/{dataset_name}/fold{fold}/features/modalities/{modality}/training.npz",
        output_features_test = OUTPUT_ROOT + "/spectre/{epoch}/{dataset_name}/fold{fold}/features/modalities/{modality}/test.npz"
    resources:
        image = "jtagscherer/evalblocks-spectre:0.0.1",
        qos="low",
        cpus=16,
        gpus=1,
        mem_mb=32000,
        time="1-00:00:00"
    shell:
        """
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m featuremodels.scripts.spectre \
                --entries-file {input.entries_file} \
                --output-features-training {output.output_features_training} \
                --output-features-test {output.output_features_test} \
                --modality {wildcards.modality}"
        """

rule compute_features_tapct:
    input:
        entries_file = lambda wildcards: DATASET_ROOT + f"/{wildcards.dataset_name}/{get_entries_file('curia', wildcards.dataset_name)}_fold{wildcards.fold}.json"
    output:
        output_features_training = OUTPUT_ROOT + "/tapct/{epoch}/{dataset_name}/fold{fold}/features/modalities/{modality}/training.npz",
        output_features_test = OUTPUT_ROOT + "/tapct/{epoch}/{dataset_name}/fold{fold}/features/modalities/{modality}/test.npz"
    resources:
        image = "jtagscherer/evalblocks-huggingface:0.0.1",
        qos="low",
        cpus=16,
        gpus=1,
        mem_mb=32000,
        time="1-00:00:00"
    shell:
        """
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "export HF_HOME={HF_HOME} && \
            cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m featuremodels.scripts.tapct \
                --entries-file {input.entries_file} \
                --output-features-training {output.output_features_training} \
                --output-features-test {output.output_features_test} \
                --modality {wildcards.modality}"
        """
