# Copyright Diagnostic Image Analysis Group, Radboudumc, Nijmegen, The Netherlands
# Licensed under Apache-2.0

from util.snakemake_helpers import VALID_ORGANS

rule compute_features_ctfm:
    input:
        scan_path = lambda wildcards: DATASET_ROOT + f"/LEAVS/imagesTr/{wildcards.scan_id}.nii.gz" if wildcards.split != "test" else DATASET_ROOT + f"/LEAVS/imagesTs/{wildcards.scan_id}.nii.gz",
        seg_path = DATASET_ROOT + "/LEAVS/AMOS-MM-TotalSegmentator/{scan_id}_segmentation.nii.gz"
    output:
        gallbladder = OUTPUT_ROOT + "/ctfm/gallbladder/{split}/features/raw/{scan_id}.npz",
        kidney_left = OUTPUT_ROOT + "/ctfm/kidney_left/{split}/features/raw/{scan_id}.npz",
        kidney_right = OUTPUT_ROOT + "/ctfm/kidney_right/{split}/features/raw/{scan_id}.npz",
        large_bowel = OUTPUT_ROOT + "/ctfm/large_bowel/{split}/features/raw/{scan_id}.npz",
        liver = OUTPUT_ROOT + "/ctfm/liver/{split}/features/raw/{scan_id}.npz",
        pancreas = OUTPUT_ROOT + "/ctfm/pancreas/{split}/features/raw/{scan_id}.npz",
        small_bowel = OUTPUT_ROOT + "/ctfm/small_bowel/{split}/features/raw/{scan_id}.npz",
        spleen = OUTPUT_ROOT + "/ctfm/spleen/{split}/features/raw/{scan_id}.npz",
        stomach = OUTPUT_ROOT + "/ctfm/stomach/{split}/features/raw/{scan_id}.npz"
    group: "featuremodels_ctfm"
    resources:
        image = "jtagscherer/evalblocks-ctfm:0.0.1",
        qos="low",
        cpus=16,
        gpus=1,
        mem_mb=32000,
        time="1-00:00:00"
    shell:
        """
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m featuremodels.scripts.ctfm \
                --scan-path {input.scan_path} \
                --seg-path {input.seg_path} \
                --output-paths gallbladder:{output.gallbladder},kidney_left:{output.kidney_left},kidney_right:{output.kidney_right},large_bowel:{output.large_bowel},liver:{output.liver},pancreas:{output.pancreas},small_bowel:{output.small_bowel},spleen:{output.spleen},stomach:{output.stomach}"
        """

rule compute_features_curia:
    input:
        scan_path = lambda wildcards: DATASET_ROOT + f"/LEAVS/imagesTr/{wildcards.scan_id}.nii.gz" if wildcards.split != "test" else DATASET_ROOT + f"/LEAVS/imagesTs/{wildcards.scan_id}.nii.gz",
        seg_path = DATASET_ROOT + "/LEAVS/AMOS-MM-TotalSegmentator/{scan_id}_segmentation.nii.gz"
    output:
        gallbladder = OUTPUT_ROOT + "/curia/gallbladder/{split}/features/raw/{scan_id}.npz",
        kidney_left = OUTPUT_ROOT + "/curia/kidney_left/{split}/features/raw/{scan_id}.npz",
        kidney_right = OUTPUT_ROOT + "/curia/kidney_right/{split}/features/raw/{scan_id}.npz",
        large_bowel = OUTPUT_ROOT + "/curia/large_bowel/{split}/features/raw/{scan_id}.npz",
        liver = OUTPUT_ROOT + "/curia/liver/{split}/features/raw/{scan_id}.npz",
        pancreas = OUTPUT_ROOT + "/curia/pancreas/{split}/features/raw/{scan_id}.npz",
        small_bowel = OUTPUT_ROOT + "/curia/small_bowel/{split}/features/raw/{scan_id}.npz",
        spleen = OUTPUT_ROOT + "/curia/spleen/{split}/features/raw/{scan_id}.npz",
        stomach = OUTPUT_ROOT + "/curia/stomach/{split}/features/raw/{scan_id}.npz"
    group: "featuremodels_curia"
    resources:
        image = "jtagscherer/evalblocks-huggingface:0.0.1",
        qos="low",
        cpus=16,
        gpus=1,
        mem_mb=32000,
        time="1-00:00:00"
    shell:
        """
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "export HF_HOME={HF_HOME} && \
            cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m featuremodels.scripts.curia \
                --scan-path {input.scan_path} \
                --seg-path {input.seg_path} \
                --output-paths gallbladder:{output.gallbladder},kidney_left:{output.kidney_left},kidney_right:{output.kidney_right},large_bowel:{output.large_bowel},liver:{output.liver},pancreas:{output.pancreas},small_bowel:{output.small_bowel},spleen:{output.spleen},stomach:{output.stomach}"
        """

rule compute_features_umedpt:
    input:
        scan_path = lambda wildcards: DATASET_ROOT + f"/LEAVS/imagesTr/{wildcards.scan_id}.nii.gz" if wildcards.split != "test" else DATASET_ROOT + f"/LEAVS/imagesTs/{wildcards.scan_id}.nii.gz",
        seg_path = DATASET_ROOT + "/LEAVS/AMOS-MM-TotalSegmentator/{scan_id}_segmentation.nii.gz"
    output:
        gallbladder = OUTPUT_ROOT + "/umedpt/gallbladder/{split}/features/raw/{scan_id}.npz",
        kidney_left = OUTPUT_ROOT + "/umedpt/kidney_left/{split}/features/raw/{scan_id}.npz",
        kidney_right = OUTPUT_ROOT + "/umedpt/kidney_right/{split}/features/raw/{scan_id}.npz",
        large_bowel = OUTPUT_ROOT + "/umedpt/large_bowel/{split}/features/raw/{scan_id}.npz",
        liver = OUTPUT_ROOT + "/umedpt/liver/{split}/features/raw/{scan_id}.npz",
        pancreas = OUTPUT_ROOT + "/umedpt/pancreas/{split}/features/raw/{scan_id}.npz",
        small_bowel = OUTPUT_ROOT + "/umedpt/small_bowel/{split}/features/raw/{scan_id}.npz",
        spleen = OUTPUT_ROOT + "/umedpt/spleen/{split}/features/raw/{scan_id}.npz",
        stomach = OUTPUT_ROOT + "/umedpt/stomach/{split}/features/raw/{scan_id}.npz"
    group: "featuremodels_umedpt"
    resources:
        image = "jtagscherer/evalblocks-umedpt:0.0.1",
        qos="low",
        cpus=16,
        gpus=1,
        mem_mb=32000,
        time="1-00:00:00"
    shell:
        """
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m featuremodels.scripts.umedpt \
                --scan-path {input.scan_path} \
                --seg-path {input.seg_path} \
                --output-paths gallbladder:{output.gallbladder},kidney_left:{output.kidney_left},kidney_right:{output.kidney_right},large_bowel:{output.large_bowel},liver:{output.liver},pancreas:{output.pancreas},small_bowel:{output.small_bowel},spleen:{output.spleen},stomach:{output.stomach}"
        """

rule compute_features_spectre:
    input:
        scan_path = lambda wildcards: DATASET_ROOT + f"/LEAVS/imagesTr/{wildcards.scan_id}.nii.gz" if wildcards.split != "test" else DATASET_ROOT + f"/LEAVS/imagesTs/{wildcards.scan_id}.nii.gz",
        seg_path = DATASET_ROOT + "/LEAVS/AMOS-MM-TotalSegmentator/{scan_id}_segmentation.nii.gz"
    output:
        gallbladder = OUTPUT_ROOT + "/spectre/gallbladder/{split}/features/raw/{scan_id}.npz",
        kidney_left = OUTPUT_ROOT + "/spectre/kidney_left/{split}/features/raw/{scan_id}.npz",
        kidney_right = OUTPUT_ROOT + "/spectre/kidney_right/{split}/features/raw/{scan_id}.npz",
        large_bowel = OUTPUT_ROOT + "/spectre/large_bowel/{split}/features/raw/{scan_id}.npz",
        liver = OUTPUT_ROOT + "/spectre/liver/{split}/features/raw/{scan_id}.npz",
        pancreas = OUTPUT_ROOT + "/spectre/pancreas/{split}/features/raw/{scan_id}.npz",
        small_bowel = OUTPUT_ROOT + "/spectre/small_bowel/{split}/features/raw/{scan_id}.npz",
        spleen = OUTPUT_ROOT + "/spectre/spleen/{split}/features/raw/{scan_id}.npz",
        stomach = OUTPUT_ROOT + "/spectre/stomach/{split}/features/raw/{scan_id}.npz"
    group: "featuremodels_spectre"
    resources:
        image = "jtagscherer/evalblocks-spectre:0.0.1",
        qos="low",
        cpus=16,
        gpus=1,
        mem_mb=32000,
        time="1-00:00:00"
    shell:
        """
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m featuremodels.scripts.spectre \
                --scan-path {input.scan_path} \
                --seg-path {input.seg_path} \
                --output-paths gallbladder:{output.gallbladder},kidney_left:{output.kidney_left},kidney_right:{output.kidney_right},large_bowel:{output.large_bowel},liver:{output.liver},pancreas:{output.pancreas},small_bowel:{output.small_bowel},spleen:{output.spleen},stomach:{output.stomach}"
        """

rule compute_features_tapct:
    input:
        scan_path = lambda wildcards: DATASET_ROOT + f"/LEAVS/imagesTr/{wildcards.scan_id}.nii.gz" if wildcards.split != "test" else DATASET_ROOT + f"/LEAVS/imagesTs/{wildcards.scan_id}.nii.gz",
        seg_path = DATASET_ROOT + "/LEAVS/AMOS-MM-TotalSegmentator/{scan_id}_segmentation.nii.gz"
    output:
        gallbladder = OUTPUT_ROOT + "/tapct/gallbladder/{split}/features/raw/{scan_id}.npz",
        kidney_left = OUTPUT_ROOT + "/tapct/kidney_left/{split}/features/raw/{scan_id}.npz",
        kidney_right = OUTPUT_ROOT + "/tapct/kidney_right/{split}/features/raw/{scan_id}.npz",
        large_bowel = OUTPUT_ROOT + "/tapct/large_bowel/{split}/features/raw/{scan_id}.npz",
        liver = OUTPUT_ROOT + "/tapct/liver/{split}/features/raw/{scan_id}.npz",
        pancreas = OUTPUT_ROOT + "/tapct/pancreas/{split}/features/raw/{scan_id}.npz",
        small_bowel = OUTPUT_ROOT + "/tapct/small_bowel/{split}/features/raw/{scan_id}.npz",
        spleen = OUTPUT_ROOT + "/tapct/spleen/{split}/features/raw/{scan_id}.npz",
        stomach = OUTPUT_ROOT + "/tapct/stomach/{split}/features/raw/{scan_id}.npz"
    group: "featuremodels.tapct"
    resources:
        image = "jtagscherer/evalblocks-huggingface:0.0.1",
        qos="low",
        cpus=16,
        gpus=1,
        mem_mb=32000,
        time="1-00:00:00"
    shell:
        """
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "export HF_HOME={HF_HOME} && \
            cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m featuremodels.scripts.tapct \
                --scan-path {input.scan_path} \
                --seg-path {input.seg_path} \
                --output-paths gallbladder:{output.gallbladder},kidney_left:{output.kidney_left},kidney_right:{output.kidney_right},large_bowel:{output.large_bowel},liver:{output.liver},pancreas:{output.pancreas},small_bowel:{output.small_bowel},spleen:{output.spleen},stomach:{output.stomach}"
        """
