# Copyright Diagnostic Image Analysis Group, Radboudumc, Nijmegen, The Netherlands
# Licensed under Apache-2.0

from util.snakemake_helpers import VALID_ORGANS


def get_batch_ids_for_model_split_organ(model_name, split, organ_name):
    """Get all batch IDs for a given model/split/organ combination - harmonized with feature models."""
    scans = get_scans_for_split_and_organ(split, organ_name)
    scan_batches = create_batches(scans, BATCH_SIZE)
    batch_ids = []
    for batch_idx in range(len(scan_batches)):
        batch_id = get_batch_id(batch_idx, len(scan_batches))
        batch_ids.append(batch_id)
    return batch_ids


def get_scans_for_batch(model_name, split, organ_name, batch_id):
    """Get scan IDs for a specific batch - harmonized with feature models."""
    scans = get_scans_for_split_and_organ(split, organ_name)
    scan_batches = create_batches(scans, BATCH_SIZE)
    batch_idx = int(batch_id.split("_")[1])
    return scan_batches[batch_idx]


def get_progress_file(wildcards):
    """Get the progress file that indicates feature model completion."""
    return OUTPUT_ROOT + f"/{wildcards.model_name}/progress/{wildcards.split}/{wildcards.organ_name}/{wildcards.batch_id}_features.done"


def get_input_feature_paths_for_batch(wildcards):
    """Get input feature paths for aggregation for a batch."""
    batch_scans = get_scans_for_batch(wildcards.model_name, wildcards.split, wildcards.organ_name, wildcards.batch_id)
    
    input_paths = []
    for scan_id in batch_scans:
        input_path = OUTPUT_ROOT + f"/{wildcards.model_name}/{wildcards.organ_name}/{wildcards.split}/features/raw/{scan_id}.npz"
        input_paths.append(input_path)
    return input_paths


def join_input_features_mean(wildcards):
    """Join input feature paths for mean aggregation."""
    return "\n".join(get_input_feature_paths_for_batch(wildcards))


def join_input_features_max(wildcards):
    """Join input feature paths for max aggregation."""
    return "\n".join(get_input_feature_paths_for_batch(wildcards))


rule aggregate_mean:
    input:
        progress_file = get_progress_file
    output:
        progress_file_agg = OUTPUT_ROOT + "/{model_name}/progress/{split}/{organ_name}/{batch_id}_mean.done"
    resources:
        image = "jtagscherer/evalblocks-core:0.0.1",
        qos="idle",
        cpus=8,
        gpus=0,
        mem_mb=16000,
        time="1-00:00:00"
    params:
        input_features_str = join_input_features_mean
    shell:
        """
        input_features_file=$(mktemp /tmp/input_features.XXXXXX)
        cat > "$input_features_file" << 'EOF_INPUT_FEATURES'
{params.input_features_str}
EOF_INPUT_FEATURES
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m aggregation.scripts.mean \
                --input-features-file $input_features_file \
                --output-root {OUTPUT_ROOT} \
                --model-name {wildcards.model_name} \
                --split {wildcards.split} \
                --organ-name {wildcards.organ_name} \
                --aggregation-method mean && \
            rm -f $input_features_file && \
            mkdir -p $(dirname {output.progress_file_agg}) && \
            touch {output.progress_file_agg}"
        """

rule aggregate_max:
    input:
        progress_file = get_progress_file
    output:
        progress_file_agg = OUTPUT_ROOT + "/{model_name}/progress/{split}/{organ_name}/{batch_id}_max.done"
    resources:
        image = "jtagscherer/evalblocks-core:0.0.1",
        qos="idle",
        cpus=8,
        gpus=0,
        mem_mb=16000,
        time="1-00:00:00"
    params:
        input_features_str = join_input_features_max
    shell:
        """
        input_features_file=$(mktemp /tmp/input_features.XXXXXX)
        cat > "$input_features_file" << 'EOF_INPUT_FEATURES'
{params.input_features_str}
EOF_INPUT_FEATURES
        ./run_from_repository.sh "{REPOSITORY_ROOT}" \
            "cd {REPOSITORY_ROOT} && \
            /usr/local/bin/python3 -m aggregation.scripts.max \
                --input-features-file $input_features_file \
                --output-root {OUTPUT_ROOT} \
                --model-name {wildcards.model_name} \
                --split {wildcards.split} \
                --organ-name {wildcards.organ_name} \
                --aggregation-method max && \
            rm -f $input_features_file && \
            mkdir -p $(dirname {output.progress_file_agg}) && \
            touch {output.progress_file_agg}"
        """
